In [1]:
import pandas as pd
import numpy as np

In [2]:
df_train = pd.read_csv("train.csv")
df_valid = pd.read_csv("valid.csv")
df_test = pd.read_csv("test.csv")

df_full = pd.concat([df_train, df_valid, df_test])
df_full.head()

,filename,width,height,class,xmin,ymin,xmax,ymax
0,rpa_aa_25C_3_dpf_fert_04_24_20261207_png.rf.78...,1040,1050,Planula,630,294,641,304
1,rpa_aa_25C_3_dpf_fert_04_24_20261207_png.rf.78...,1040,1050,Planula,553,275,564,286
2,rpa_aa_25C_3_dpf_fert_04_24_20261207_png.rf.78...,1040,1050,Planula,432,284,442,294
3,rpa_aa_25C_3_dpf_fert_04_24_20261207_png.rf.78...,1040,1050,Planula,167,634,177,645
4,rpa_aa_25C_3_dpf_fert_04_24_20261207_png.rf.78...,1040,1050,Planula,518,385,529,396

In [3]:
df_full.iloc[0]["filename"]

'rpa_aa_25C_3_dpf_fert_04_24_20261207_png.rf.78KsdV32DeHml9aoCnb8.png'

In [4]:
df_full = df_full.filter(items=["filename", "class", "xmin", "ymin", "xmax", "ymax"])
df_full.columns = ["image_filename", "class", "x1", "y1", "x2", "y2"]
df_full.head()

,image_filename,class,x1,y1,x2,y2
0,rpa_aa_25C_3_dpf_fert_04_24_20261207_png.rf.78...,Planula,630,294,641,304
1,rpa_aa_25C_3_dpf_fert_04_24_20261207_png.rf.78...,Planula,553,275,564,286
2,rpa_aa_25C_3_dpf_fert_04_24_20261207_png.rf.78...,Planula,432,284,442,294
3,rpa_aa_25C_3_dpf_fert_04_24_20261207_png.rf.78...,Planula,167,634,177,645
4,rpa_aa_25C_3_dpf_fert_04_24_20261207_png.rf.78...,Planula,518,385,529,396

In [5]:
current_fname = df_full.iloc[0]["image_filename"][:-28]
current_fname = current_fname[:-4] + ".png"
current_fname

'rpa_aa_25C_3_dpf_fert_04_24_20261207.png'

In [6]:
filenames_formatted = []
for i in range(len(df_full)):
    current_fname = df_full.iloc[i]["image_filename"][:-28]
    current_fname = current_fname[:-4] + ".png"
    filenames_formatted.append(current_fname)

df_full["image_filename"] = filenames_formatted
df_full.head()

                             image_filename    class   x1   y1   x2   y2
0  rpa_aa_25C_3_dpf_fert_04_24_20261207.png  Planula  630  294  641  304
1  rpa_aa_25C_3_dpf_fert_04_24_20261207.png  Planula  553  275  564  286
2  rpa_aa_25C_3_dpf_fert_04_24_20261207.png  Planula  432  284  442  294
3  rpa_aa_25C_3_dpf_fert_04_24_20261207.png  Planula  167  634  177  645
4  rpa_aa_25C_3_dpf_fert_04_24_20261207.png  Planula  518  385  529  396

In [7]:
uniq_starts = set([f[:-8] for f in filenames_formatted])
uniq_starts

{'glw_ac_25c_3_dpf_fert_04_24_2026',
 'rpa_aa_25C_3_dpf_fert_04_24_2026',
 'rpa_aa_25C_6_dpf_fert_04_24_2026',
 'rpa_bb_25C_6_dpf_fert_04_24_2026',
 'wt_25c_7_dpf_fert_04_24_2026'}

In [8]:
df_formatted = df_full
contains_start = ['glw_ac_25c_3_dpf_fert_04_24_2026' in f for f in filenames_formatted]
df_formatted["contains_start"] = contains_start
df_formatted.shape

(176302, 7)

In [9]:
df_formatted[df_formatted["contains_start"] == True]

,image_filename,class,x1,y1,x2,y2,contains_start
1067,glw_ac_25c_3_dpf_fert_04_24_20260113.png,Planula,83,572,94,582,True
1068,glw_ac_25c_3_dpf_fert_04_24_20260113.png,Planula,800,634,812,647,True
1069,glw_ac_25c_3_dpf_fert_04_24_20260113.png,Planula,600,375,612,386,True
1070,glw_ac_25c_3_dpf_fert_04_24_20260113.png,Planula,522,540,536,553,True
1071,glw_ac_25c_3_dpf_fert_04_24_20260113.png,Planula,524,353,536,366,True
...,...,...,...,...,...,...,...
27961,glw_ac_25c_3_dpf_fert_04_24_20261749.png,Planula,89,514,97,523,True
27962,glw_ac_25c_3_dpf_fert_04_24_20261749.png,Planula,575,363,586,374,True
27963,glw_ac_25c_3_dpf_fert_04_24_20261749.png,Planula,466,210,480,222,True
27964,glw_ac_25c_3_dpf_fert_04_24_20261749.png,Planula,796,301,809,313,True
27965,glw_ac_25c_3_dpf_fert_04_24_20261749.png,Planula,656,549,665,558,True

In [10]:
for start in uniq_starts:
    df_formatted = df_full
    contains_start = [start in f for f in filenames_formatted]
    df_formatted["contains_start"] = contains_start
    df_formatted = df_formatted[df_formatted["contains_start"] == True]
    df_formatted = df_formatted.filter(items=["image_filename", "class", "x1", "y1", "x2", "y2"])

    print("Saving " + start)
    df_formatted.to_csv(start + "_annotations.csv", index=False)

Saving rpa_aa_25C_3_dpf_fert_04_24_2026
Saving rpa_bb_25C_6_dpf_fert_04_24_2026
Saving rpa_aa_25C_6_dpf_fert_04_24_2026
Saving wt_25c_7_dpf_fert_04_24_2026
Saving glw_ac_25c_3_dpf_fert_04_24_2026