In [1]:
import ultralytics
from ultralytics import YOLO
from PIL import Image, ImageDraw, ImageFont
import requests

import os
import cv2

from matplotlib import patches, text, patheffects
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import shutil
import yaml

ultralytics.checks()

Ultralytics 8.4.63 🚀 Python-3.13.1 torch-2.6.0 CPU (Apple M2 Pro)
Setup complete ✅ (10 CPUs, 16.0 GB RAM, 305.1/460.4 GB disk)

# Training
Only run this portion once!

In [5]:
model = YOLO("yolo26n.pt")
results = model.train(data="/Users/jonathanzhu/nematostella_videos/labeled_data/NematostellaTracking.yolo26/data.yaml", epochs=10, device='mps')

Ultralytics 8.4.63 🚀 Python-3.13.1 torch-2.6.0 MPS (Apple M2 Pro)
engine/trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=16, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/Users/jonathanzhu/nematostella_videos/labeled_data/NematostellaTracking.yolo26/data.yaml, degrees=0.0, deterministic=True, device=mps, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=10, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolo26n.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=train-4, nbs=64, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=/Users/jonathanzhu/Documents/GitHub/nematostellatracking/video_analysis/runs/detect/train-4, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=2

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      6640  ultralytics.nn.modules.block.C3k2            [32, 64, 1, False, 0.25]
  3                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
  4                  -1  1     26080  ultralytics.nn.modules.block.C3k2            [64, 128, 1, False, 0.25]
  5                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
  6                  -1  1     87040  ultralytics.nn.modules.block.C3k2            [128, 128, 1, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    346112  ultralytics.nn.modules.block.C3k2            [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5, 3, True]
 10                  -1  1    249728  ultralytics.nn.modules.block.C2PSA           [256, 256, 1]
 11                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 12             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 13                  -1  1    119808  ultralytics.nn.modules.block.C3k2            [384, 128, 1, True]
 14                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 15             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 16                  -1  1     34304  ultralytics.nn.modules.block.C3k2            [256, 64, 1, True]
 17                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 18            [-1, 13]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 19                  -1  1     95232  ultralytics.nn.modules.block.C3k2            [192, 128, 1, True]
 20                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 21            [-1, 10]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 22                  -1  1    463104  ultralytics.nn.modules.block.C3k2            [384, 256, 1, True, 0.5, True]
 23        [16, 19, 22]  1    241956  ultralytics.nn.modules.head.Detect           [2, 1, True, [64, 128, 256]]
YOLO26n summary: 260 layers, 2,504,580 parameters, 2,504,580 gradients, 5.8 GFLOPs

Transferred 606/708 items from pretrained weights
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 473.5±170.0 MB/s, size: 110.7 KB)
train: Scanning /Users/jonathanzhu/nematostella_videos/labeled_data/NematostellaTracking.yolo26/train/labels... 5037 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 5037/5037 1.7Kit/s 2.9s0.1s
train: New cache created: /Users/jonathanzhu/nematostella_videos/labeled_data/NematostellaTracking.yolo26/train/labels.cache
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 361.4±117.7 MB/s, size: 104.7 KB)
val: Scanning /Users/jonathanzhu/nematostella_videos/labeled_data/NematostellaTracking.yolo26/valid/labels... 1080 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1080/1080 1.8Kit/s 0.6s1ss
val: New cache created: /Users/jonathanzhu/nematostella_videos/labeled_data/NematostellaTracking.yolo26/valid/labels.cache
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.001667, momentum=0.9) with parameter groups 114 weight(decay=0.0), 126 weight(decay=0.0005), 126 bias(decay=0.0)
Plotting labels to /Users/jonathanzhu/Documents/GitHub/nematostellatracking/video_analysis/runs/detect/train-4/labels.jpg...
Image sizes 640 train, 640 val
Using 0 dataloader workers
Logging results to /Users/jonathanzhu/Documents/GitHub/nematostellatracking/video_analysis/runs/detect/train-4
Starting training for 10 epochs...
Closing dataloader mosaic

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

/opt/anaconda3/envs/nndl-env/lib/python3.13/site-packages/ultralytics/utils/tal.py:195: UserWarning: MPS: nonzero op is supported natively starting from macOS 14.0. Falling back on CPU. This may have performance implications. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/native/mps/operations/Indexing.mm:401.)
  bbox_scores[mask_gt] = pd_scores[ind[0], :, ind[1]][mask_gt]  # b, max_num_obj, h*w

       1/10      6.27G      1.447      1.738  0.0009913        252        640: 100% ━━━━━━━━━━━━ 315/315 1.7s/it 8:42<1.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 34/34 3.5s/it 1:582.7sss
                   all       1080      21249      0.902      0.815      0.942      0.678

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/10      7.09G      1.175     0.6848  0.0007773        232        640: 100% ━━━━━━━━━━━━ 315/315 1.9s/it 9:45<2.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 34/34 4.3s/it 2:253.1ss
                   all       1080      21249       0.96      0.941      0.988      0.757

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/10       7.9G      1.101     0.4759  0.0007225        240        640: 100% ━━━━━━━━━━━━ 315/315 1.8s/it 9:13<2.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 34/34 4.3s/it 2:272.8ss
                   all       1080      21249      0.966      0.908      0.987      0.778

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/10      8.75G      1.032      0.383  0.0006728        237        640: 100% ━━━━━━━━━━━━ 315/315 1.8s/it 9:33<1.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 34/34 3.1s/it 1:472.7sss
                   all       1080      21249      0.979      0.964      0.992       0.76

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/10      9.67G     0.9617     0.3344  0.0006259        248        640: 100% ━━━━━━━━━━━━ 315/315 2.1s/it 11:14<2.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 34/34 2.4s/it 1:221.5sss
                   all       1080      21249      0.971      0.976      0.993      0.769

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/10      10.6G      0.926     0.3065  0.0006008        244        640: 100% ━━━━━━━━━━━━ 315/315 2.2s/it 11:32<1.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 34/34 2.5s/it 1:251.1sss
                   all       1080      21249      0.988      0.984      0.994      0.791

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/10      11.5G     0.8887     0.2866   0.000574        240        640: 100% ━━━━━━━━━━━━ 315/315 2.3s/it 11:49<2.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 34/34 2.2s/it 1:141.4sss
                   all       1080      21249       0.99      0.981      0.994      0.777

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/10      12.4G     0.8447     0.2716  0.0005522        233        640: 100% ━━━━━━━━━━━━ 315/315 2.7s/it 14:01<3.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 34/34 2.3s/it 1:181.5sss
                   all       1080      21249      0.991      0.986      0.994      0.809

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/10      13.2G     0.8316     0.2628  0.0005329        235        640: 100% ━━━━━━━━━━━━ 315/315 2.5s/it 13:02<2.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 34/34 1.5s/it 49.5s1.0ss
                   all       1080      21249      0.984      0.986      0.994      0.815

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/10        14G     0.7791       0.25  0.0005053        252        640: 100% ━━━━━━━━━━━━ 315/315 2.4s/it 12:48<2.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 34/34 1.7s/it 56.1s1.1ss
                   all       1080      21249       0.99      0.987      0.994      0.785

10 epochs completed in 2.153 hours.
Optimizer stripped from /Users/jonathanzhu/Documents/GitHub/nematostellatracking/video_analysis/runs/detect/train-4/weights/last.pt, 5.4MB
Optimizer stripped from /Users/jonathanzhu/Documents/GitHub/nematostellatracking/video_analysis/runs/detect/train-4/weights/best.pt, 5.4MB

Validating /Users/jonathanzhu/Documents/GitHub/nematostellatracking/video_analysis/runs/detect/train-4/weights/best.pt...
Ultralytics 8.4.63 🚀 Python-3.13.1 torch-2.6.0 MPS (Apple M2 Pro)
YOLO26n summary (fused): 122 layers, 2,375,226 parameters, 0 gradients, 5.2 GFLOPs
WARNING ⚠️ NMS time limit 2.050s exceeded
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 34/34 2.6s/it 1:281.0sss
                   all       1080      21249      0.984      0.986      0.994      0.815
               Planula       1080      13176      0.988      0.984      0.994       0.79
                 Polyp        710       8073       0.98      0.988      0.994      0.839
Speed: 0.7ms preprocess, 26.5ms inference, 0.0ms loss, 0.7ms postprocess per image
Results saved to /Users/jonathanzhu/Documents/GitHub/nematostellatracking/video_analysis/runs/detect/train-4

Loss Metrics: (lower being better)
- `box_loss` is a metric that refers to how well the model predicts positions. 
- `cls_loss` or classification loss refers to how well the model predicts what is in each box.
- `dfl_loss` or Distribution Focal Loss refers to how well the model is refining. 

Post-Epoch Metrics: (scaled from 0 to 1, with 1 being better)
- `P` refers to precision. It measures what percentage of the model's predictions are correct.
- `R` refers to recall. It measures what percentage of actual objects the model predicted.
- `mAP50` and `mAP50-95` are similar and refer to mean average precision, measuring Intersection over Union, where we see how much overlap there is on predicted boxes versus actual boxes. mAP50-95 is more strict and we should hope for a high value for this.

# Preliminary Results (numeric metrics)

In [4]:
best_model = YOLO("runs/detect/train-4/weights/best.pt")
train_results = best_model.val(data="/Users/jonathanzhu/nematostella_videos/labeled_data/NematostellaTracking.yolo26/data.yaml", device='mps', split='train')
val_results = best_model.val(data="/Users/jonathanzhu/nematostella_videos/labeled_data/NematostellaTracking.yolo26/data.yaml", device='mps', split='val')
test_results = best_model.val(data="/Users/jonathanzhu/nematostella_videos/labeled_data/NematostellaTracking.yolo26/data.yaml", device='mps', split='test')

Ultralytics 8.4.63 🚀 Python-3.13.1 torch-2.6.0 MPS (Apple M2 Pro)
YOLO26n summary (fused): 122 layers, 2,375,226 parameters, 0 gradients, 5.2 GFLOPs
val: Fast image access ✅ (ping: 0.2±0.2 ms, read: 526.8±113.3 MB/s, size: 97.9 KB)
val: Scanning /Users/jonathanzhu/nematostella_videos/labeled_data/NematostellaTracking.yolo26/train/labels.cache... 5037 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 5037/5037 391.2Mit/s 0.0s

/opt/anaconda3/envs/nndl-env/lib/python3.13/site-packages/ultralytics/utils/nms.py:95: UserWarning: MPS: nonzero op is supported natively starting from macOS 14.0. Falling back on CPU. This may have performance implications. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/native/mps/operations/Indexing.mm:401.)
  x = x[filt]

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 315/315 3.0it/s 1:46<0.3ss
                   all       5037      99642      0.983      0.988      0.994      0.817
               Planula       5037      75000      0.987      0.989      0.994      0.793
                 Polyp       2174      24642      0.979      0.987      0.994      0.841
Speed: 0.2ms preprocess, 5.2ms inference, 0.0ms loss, 0.5ms postprocess per image
Results saved to /Users/jonathanzhu/Documents/GitHub/nematostellatracking/video_analysis/runs/detect/val
Ultralytics 8.4.63 🚀 Python-3.13.1 torch-2.6.0 MPS (Apple M2 Pro)
val: Fast image access ✅ (ping: 0.2±0.1 ms, read: 474.5±211.3 MB/s, size: 117.5 KB)
val: Scanning /Users/jonathanzhu/nematostella_videos/labeled_data/NematostellaTracking.yolo26/valid/labels.cache... 1080 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1080/1080 156.2Mit/s 0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 68/68 2.9it/s 23.7s0.3ss
                   all       1080      21249      0.984      0.986      0.994      0.815
               Planula       1080      13176      0.988      0.984      0.994       0.79
                 Polyp        710       8073       0.98      0.988      0.994      0.839
Speed: 0.2ms preprocess, 5.7ms inference, 0.0ms loss, 0.5ms postprocess per image
Results saved to /Users/jonathanzhu/Documents/GitHub/nematostellatracking/video_analysis/runs/detect/val-2
Ultralytics 8.4.63 🚀 Python-3.13.1 torch-2.6.0 MPS (Apple M2 Pro)
val: Fast image access ✅ (ping: 0.0±0.1 ms, read: 520.6±156.2 MB/s, size: 139.3 KB)
val: Scanning /Users/jonathanzhu/nematostella_videos/labeled_data/NematostellaTracking.yolo26/test/labels... 1079 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1079/1079 1.8Kit/s 0.6s0.0s
val: New cache created: /Users/jonathanzhu/nematostella_videos/labeled_data/NematostellaTracking.yolo26/test/labels.cache
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 68/68 3.0it/s 23.0s0.3ss
                   all       1079      21225      0.986      0.982      0.994      0.816
               Planula       1079      13087      0.989      0.981      0.994      0.794
                 Polyp        714       8138      0.983      0.982      0.994      0.838
Speed: 0.2ms preprocess, 5.6ms inference, 0.0ms loss, 0.4ms postprocess per image
Results saved to /Users/jonathanzhu/Documents/GitHub/nematostellatracking/video_analysis/runs/detect/val-3

In [5]:
print("Class indices with average precision:", test_results.ap_class_index)
print("Average precision for all classes:", test_results.box.all_ap)
print("Average precision:", test_results.box.ap)
print("Average precision at IoU=0.50:", test_results.box.ap50)
print("Class indices for average precision:", test_results.box.ap_class_index)
print("Class-specific results:", test_results.box.class_result)
print("F1 score:", test_results.box.f1)
print("F1 score curve:", test_results.box.f1_curve)
print("Overall fitness score:", test_results.box.fitness)
print("Mean average precision:", test_results.box.map)
print("Mean average precision at IoU=0.50:", test_results.box.map50)
print("Mean average precision at IoU=0.75:", test_results.box.map75)
print("Mean average precision for different IoU thresholds:", test_results.box.maps)
print("Mean results for different metrics:", test_results.box.mean_results)
print("Mean precision:", test_results.box.mp)
print("Mean recall:", test_results.box.mr)
print("Precision:", test_results.box.p)
print("Precision curve:", test_results.box.p_curve)
print("Precision values:", test_results.box.prec_values)
print("Specific precision metrics:", test_results.box.px)
print("Recall:", test_results.box.r)
print("Recall curve:", test_results.box.r_curve)

Class indices with average precision: [0 1]
Average precision for all classes: [[    0.99415     0.99389     0.99295     0.99004     0.97503     0.94005     0.87031     0.72438      0.4228    0.032547]
 [      0.994     0.99392     0.99337     0.99211     0.98958     0.97749     0.96073     0.87774     0.54676    0.058056]]
Average precision: [    0.79361     0.83837]
Average precision at IoU=0.50: [    0.99415       0.994]
Class indices for average precision: [0 1]
Class-specific results: <bound method Metric.class_result of ultralytics.utils.metrics.Metric object with attributes:

all_ap: array([[    0.99415,     0.99389,     0.99295,     0.99004,     0.97503,     0.94005,     0.87031,     0.72438,      0.4228,    0.032547],
       [      0.994,     0.99392,     0.99337,     0.99211,     0.98958,     0.97749,     0.96073,     0.87774,     0.54676,    0.058056]])
ap: array([    0.79361,     0.83837])
ap50: array([    0.99415,       0.994])
ap_class_index: array([0, 1])
curves: []
curves_results: [[array([          0,    0.001001,    0.002002,    0.003003,    0.004004,    0.005005,    0.006006,    0.007007,    0.008008,    0.009009,     0.01001,    0.011011,    0.012012,    0.013013,    0.014014,    0.015015,    0.016016,    0.017017,    0.018018,    0.019019,     0.02002,    0.021021,    0.022022,    0.023023,
          0.024024,    0.025025,    0.026026,    0.027027,    0.028028,    0.029029,     0.03003,    0.031031,    0.032032,    0.033033,    0.034034,    0.035035,    0.036036,    0.037037,    0.038038,    0.039039,     0.04004,    0.041041,    0.042042,    0.043043,    0.044044,    0.045045,    0.046046,    0.047047,
          0.048048,    0.049049,     0.05005,    0.051051,    0.052052,    0.053053,    0.054054,    0.055055,    0.056056,    0.057057,    0.058058,    0.059059,     0.06006,    0.061061,    0.062062,    0.063063,    0.064064,    0.065065,    0.066066,    0.067067,    0.068068,    0.069069,     0.07007,    0.071071,
          0.072072,    0.073073,    0.074074,    0.075075,    0.076076,    0.077077,    0.078078,    0.079079,     0.08008,    0.081081,    0.082082,    0.083083,    0.084084,    0.085085,    0.086086,    0.087087,    0.088088,    0.089089,     0.09009,    0.091091,    0.092092,    0.093093,    0.094094,    0.095095,
          0.096096,    0.097097,    0.098098,    0.099099,      0.1001,      0.1011,      0.1021,      0.1031,      0.1041,     0.10511,     0.10611,     0.10711,     0.10811,     0.10911,     0.11011,     0.11111,     0.11211,     0.11311,     0.11411,     0.11512,     0.11612,     0.11712,     0.11812,     0.11912,
           0.12012,     0.12112,     0.12212,     0.12312,     0.12412,     0.12513,     0.12613,     0.12713,     0.12813,     0.12913,     0.13013,     0.13113,     0.13213,     0.13313,     0.13413,     0.13514,     0.13614,     0.13714,     0.13814,     0.13914,     0.14014,     0.14114,     0.14214,     0.14314,
           0.14414,     0.14515,     0.14615,     0.14715,     0.14815,     0.14915,     0.15015,     0.15115,     0.15215,     0.15315,     0.15415,     0.15516,     0.15616,     0.15716,     0.15816,     0.15916,     0.16016,     0.16116,     0.16216,     0.16316,     0.16416,     0.16517,     0.16617,     0.16717,
           0.16817,     0.16917,     0.17017,     0.17117,     0.17217,     0.17317,     0.17417,     0.17518,     0.17618,     0.17718,     0.17818,     0.17918,     0.18018,     0.18118,     0.18218,     0.18318,     0.18418,     0.18519,     0.18619,     0.18719,     0.18819,     0.18919,     0.19019,     0.19119,
           0.19219,     0.19319,     0.19419,      0.1952,      0.1962,      0.1972,      0.1982,      0.1992,      0.2002,      0.2012,      0.2022,      0.2032,      0.2042,     0.20521,     0.20621,     0.20721,     0.20821,     0.20921,     0.21021,     0.21121,     0.21221,     0.21321,     0.21421,     0.21522,
           0.21622,     0.21722,     0.21822,     0.21922,     0.22022,     0.22122,     0.22222,     0.22322,     0.22422,     0.22523,     0.22623,     0.22723,     0.22823,     0.22923,     0.23023,     0.23123,     0.23223,     0.23323,     0.23423,     0.23524,     0.23624,     0.23724,     0.23824,     0.23924,
           0.24024,     0.24124,     0.24224,     0.24324,     0.24424,     0.24525,     0.24625,     0.24725,     0.24825,     0.24925,     0.25025,     0.25125,     0.25225,     0.25325,     0.25425,     0.25526,     0.25626,     0.25726,     0.25826,     0.25926,     0.26026,     0.26126,     0.26226,     0.26326,
           0.26426,     0.26527,     0.26627,     0.26727,     0.26827,     0.26927,     0.27027,     0.27127,     0.27227,     0.27327,     0.27427,     0.27528,     0.27628,     0.27728,     0.27828,     0.27928,     0.28028,     0.28128,     0.28228,     0.28328,     0.28428,     0.28529,     0.28629,     0.28729,
           0.28829,     0.28929,     0.29029,     0.29129,     0.29229,     0.29329,     0.29429,      0.2953,      0.2963,      0.2973,      0.2983,      0.2993,      0.3003,      0.3013,      0.3023,      0.3033,      0.3043,     0.30531,     0.30631,     0.30731,     0.30831,     0.30931,     0.31031,     0.31131,
           0.31231,     0.31331,     0.31431,     0.31532,     0.31632,     0.31732,     0.31832,     0.31932,     0.32032,     0.32132,     0.32232,     0.32332,     0.32432,     0.32533,     0.32633,     0.32733,     0.32833,     0.32933,     0.33033,     0.33133,     0.33233,     0.33333,     0.33433,     0.33534,
           0.33634,     0.33734,     0.33834,     0.33934,     0.34034,     0.34134,     0.34234,     0.34334,     0.34434,     0.34535,     0.34635,     0.34735,     0.34835,     0.34935,     0.35035,     0.35135,     0.35235,     0.35335,     0.35435,     0.35536,     0.35636,     0.35736,     0.35836,     0.35936,
           0.36036,     0.36136,     0.36236,     0.36336,     0.36436,     0.36537,     0.36637,     0.36737,     0.36837,     0.36937,     0.37037,     0.37137,     0.37237,     0.37337,     0.37437,     0.37538,     0.37638,     0.37738,     0.37838,     0.37938,     0.38038,     0.38138,     0.38238,     0.38338,
           0.38438,     0.38539,     0.38639,     0.38739,     0.38839,     0.38939,     0.39039,     0.39139,     0.39239,     0.39339,     0.39439,      0.3954,      0.3964,      0.3974,      0.3984,      0.3994,      0.4004,      0.4014,      0.4024,      0.4034,      0.4044,     0.40541,     0.40641,     0.40741,
           0.40841,     0.40941,     0.41041,     0.41141,     0.41241,     0.41341,     0.41441,     0.41542,     0.41642,     0.41742,     0.41842,     0.41942,     0.42042,     0.42142,     0.42242,     0.42342,     0.42442,     0.42543,     0.42643,     0.42743,     0.42843,     0.42943,     0.43043,     0.43143,
           0.43243,     0.43343,     0.43443,     0.43544,     0.43644,     0.43744,     0.43844,     0.43944,     0.44044,     0.44144,     0.44244,     0.44344,     0.44444,     0.44545,     0.44645,     0.44745,     0.44845,     0.44945,     0.45045,     0.45145,     0.45245,     0.45345,     0.45445,     0.45546,
           0.45646,     0.45746,     0.45846,     0.45946,     0.46046,     0.46146,     0.46246,     0.46346,     0.46446,     0.46547,     0.46647,     0.46747,     0.46847,     0.46947,     0.47047,     0.47147,     0.47247,     0.47347,     0.47447,     0.47548,     0.47648,     0.47748,     0.47848,     0.47948,
           0.48048,     0.48148,     0.48248,     0.48348,     0.48448,     0.48549,     0.48649,     0.48749,     0.48849,     0.48949,     0.49049,     0.49149,     0.49249,     0.49349,     0.49449,      0.4955,      0.4965,      0.4975,      0.4985,      0.4995,      0.5005,      0.5015,      0.5025,      0.5035,
            0.5045,     0.50551,     0.50651,     0.50751,     0.50851,     0.50951,     0.51051,     0.51151,     0.51251,     0.51351,     0.51451,     0.51552,     0.51652,     0.51752,     0.51852,     0.51952,     0.52052,     0.52152,     0.52252,     0.52352,     0.52452,     0.52553,     0.52653,     0.52753,
           0.52853,     0.52953,     0.53053,     0.53153,     0.53253,     0.53353,     0.53453,     0.53554,     0.53654,     0.53754,     0.53854,     0.53954,     0.54054,     0.54154,     0.54254,     0.54354,     0.54454,     0.54555,     0.54655,     0.54755,     0.54855,     0.54955,     0.55055,     0.55155,
           0.55255,     0.55355,     0.55455,     0.55556,     0.55656,     0.55756,     0.55856,     0.55956,     0.56056,     0.56156,     0.56256,     0.56356,     0.56456,     0.56557,     0.56657,     0.56757,     0.56857,     0.56957,     0.57057,     0.57157,     0.57257,     0.57357,     0.57457,     0.57558,
           0.57658,     0.57758,     0.57858,     0.57958,     0.58058,     0.58158,     0.58258,     0.58358,     0.58458,     0.58559,     0.58659,     0.58759,     0.58859,     0.58959,     0.59059,     0.59159,     0.59259,     0.59359,     0.59459,      0.5956,      0.5966,      0.5976,      0.5986,      0.5996,
            0.6006,      0.6016,      0.6026,      0.6036,      0.6046,     0.60561,     0.60661,     0.60761,     0.60861,     0.60961,     0.61061,     0.61161,     0.61261,     0.61361,     0.61461,     0.61562,     0.61662,     0.61762,     0.61862,     0.61962,     0.62062,     0.62162,     0.62262,     0.62362,
           0.62462,     0.62563,     0.62663,     0.62763,     0.62863,     0.62963,     0.63063,     0.63163,     0.63263,     0.63363,     0.63463,     0.63564,     0.63664,     0.63764,     0.63864,     0.63964,     0.64064,     0.64164,     0.64264,     0.64364,     0.64464,     0.64565,     0.64665,     0.64765,
           0.64865,     0.64965,     0.65065,     0.65165,     0.65265,     0.65365,     0.65465,     0.65566,     0.65666,     0.65766,     0.65866,     0.65966,     0.66066,     0.66166,     0.66266,     0.66366,     0.66466,     0.66567,     0.66667,     0.66767,     0.66867,     0.66967,     0.67067,     0.67167,
           0.67267,     0.67367,     0.67467,     0.67568,     0.67668,     0.67768,     0.67868,     0.67968,     0.68068,     0.68168,     0.68268,     0.68368,     0.68468,     0.68569,     0.68669,     0.68769,     0.68869,     0.68969,     0.69069,     0.69169,     0.69269,     0.69369,     0.69469,      0.6957,
            0.6967,      0.6977,      0.6987,      0.6997,      0.7007,      0.7017,      0.7027,      0.7037,      0.7047,     0.70571,     0.70671,     0.70771,     0.70871,     0.70971,     0.71071,     0.71171,     0.71271,     0.71371,     0.71471,     0.71572,     0.71672,     0.71772,     0.71872,     0.71972,
           0.72072,     0.72172,     0.72272,     0.72372,     0.72472,     0.72573,     0.72673,     0.72773,     0.72873,     0.72973,     0.73073,     0.73173,     0.73273,     0.73373,     0.73473,     0.73574,     0.73674,     0.73774,     0.73874,     0.73974,     0.74074,     0.74174,     0.74274,     0.74374,
           0.74474,     0.74575,     0.74675,     0.74775,     0.74875,     0.74975,     0.75075,     0.75175,     0.75275,     0.75375,     0.75475,     0.75576,     0.75676,     0.75776,     0.75876,     0.75976,     0.76076,     0.76176,     0.76276,     0.76376,     0.76476,     0.76577,     0.76677,     0.76777,
           0.76877,     0.76977,     0.77077,     0.77177,     0.77277,     0.77377,     0.77477,     0.77578,     0.77678,     0.77778,     0.77878,     0.77978,     0.78078,     0.78178,     0.78278,     0.78378,     0.78478,     0.78579,     0.78679,     0.78779,     0.78879,     0.78979,     0.79079,     0.79179,
           0.79279,     0.79379,     0.79479,      0.7958,      0.7968,      0.7978,      0.7988,      0.7998,      0.8008,      0.8018,      0.8028,      0.8038,      0.8048,     0.80581,     0.80681,     0.80781,     0.80881,     0.80981,     0.81081,     0.81181,     0.81281,     0.81381,     0.81481,     0.81582,
           0.81682,     0.81782,     0.81882,     0.81982,     0.82082,     0.82182,     0.82282,     0.82382,     0.82482,     0.82583,     0.82683,     0.82783,     0.82883,     0.82983,     0.83083,     0.83183,     0.83283,     0.83383,     0.83483,     0.83584,     0.83684,     0.83784,     0.83884,     0.83984,
           0.84084,     0.84184,     0.84284,     0.84384,     0.84484,     0.84585,     0.84685,     0.84785,     0.84885,     0.84985,     0.85085,     0.85185,     0.85285,     0.85385,     0.85485,     0.85586,     0.85686,     0.85786,     0.85886,     0.85986,     0.86086,     0.86186,     0.86286,     0.86386,
           0.86486,     0.86587,     0.86687,     0.86787,     0.86887,     0.86987,     0.87087,     0.87187,     0.87287,     0.87387,     0.87487,     0.87588,     0.87688,     0.87788,     0.87888,     0.87988,     0.88088,     0.88188,     0.88288,     0.88388,     0.88488,     0.88589,     0.88689,     0.88789,
           0.88889,     0.88989,     0.89089,     0.89189,     0.89289,     0.89389,     0.89489,      0.8959,      0.8969,      0.8979,      0.8989,      0.8999,      0.9009,      0.9019,      0.9029,      0.9039,      0.9049,     0.90591,     0.90691,     0.90791,     0.90891,     0.90991,     0.91091,     0.91191,
           0.91291,     0.91391,     0.91491,     0.91592,     0.91692,     0.91792,     0.91892,     0.91992,     0.92092,     0.92192,     0.92292,     0.92392,     0.92492,     0.92593,     0.92693,     0.92793,     0.92893,     0.92993,     0.93093,     0.93193,     0.93293,     0.93393,     0.93493,     0.93594,
           0.93694,     0.93794,     0.93894,     0.93994,     0.94094,     0.94194,     0.94294,     0.94394,     0.94494,     0.94595,     0.94695,     0.94795,     0.94895,     0.94995,     0.95095,     0.95195,     0.95295,     0.95395,     0.95495,     0.95596,     0.95696,     0.95796,     0.95896,     0.95996,
           0.96096,     0.96196,     0.96296,     0.96396,     0.96496,     0.96597,     0.96697,     0.96797,     0.96897,     0.96997,     0.97097,     0.97197,     0.97297,     0.97397,     0.97497,     0.97598,     0.97698,     0.97798,     0.97898,     0.97998,     0.98098,     0.98198,     0.98298,     0.98398,
           0.98498,     0.98599,     0.98699,     0.98799,     0.98899,     0.98999,     0.99099,     0.99199,     0.99299,     0.99399,     0.99499,       0.996,       0.997,       0.998,       0.999,           1]), array([[          1,           1,           1, ...,           0,           0,           0],
       [          1,           1,           1, ...,     0.90486,     0.87372,           0]], shape=(2, 1000)), 'Recall', 'Precision'], [array([          0,    0.001001,    0.002002,    0.003003,    0.004004,    0.005005,    0.006006,    0.007007,    0.008008,    0.009009,     0.01001,    0.011011,    0.012012,    0.013013,    0.014014,    0.015015,    0.016016,    0.017017,    0.018018,    0.019019,     0.02002,    0.021021,    0.022022,    0.023023,
          0.024024,    0.025025,    0.026026,    0.027027,    0.028028,    0.029029,     0.03003,    0.031031,    0.032032,    0.033033,    0.034034,    0.035035,    0.036036,    0.037037,    0.038038,    0.039039,     0.04004,    0.041041,    0.042042,    0.043043,    0.044044,    0.045045,    0.046046,    0.047047,
          0.048048,    0.049049,     0.05005,    0.051051,    0.052052,    0.053053,    0.054054,    0.055055,    0.056056,    0.057057,    0.058058,    0.059059,     0.06006,    0.061061,    0.062062,    0.063063,    0.064064,    0.065065,    0.066066,    0.067067,    0.068068,    0.069069,     0.07007,    0.071071,
          0.072072,    0.073073,    0.074074,    0.075075,    0.076076,    0.077077,    0.078078,    0.079079,     0.08008,    0.081081,    0.082082,    0.083083,    0.084084,    0.085085,    0.086086,    0.087087,    0.088088,    0.089089,     0.09009,    0.091091,    0.092092,    0.093093,    0.094094,    0.095095,
          0.096096,    0.097097,    0.098098,    0.099099,      0.1001,      0.1011,      0.1021,      0.1031,      0.1041,     0.10511,     0.10611,     0.10711,     0.10811,     0.10911,     0.11011,     0.11111,     0.11211,     0.11311,     0.11411,     0.11512,     0.11612,     0.11712,     0.11812,     0.11912,
           0.12012,     0.12112,     0.12212,     0.12312,     0.12412,     0.12513,     0.12613,     0.12713,     0.12813,     0.12913,     0.13013,     0.13113,     0.13213,     0.13313,     0.13413,     0.13514,     0.13614,     0.13714,     0.13814,     0.13914,     0.14014,     0.14114,     0.14214,     0.14314,
           0.14414,     0.14515,     0.14615,     0.14715,     0.14815,     0.14915,     0.15015,     0.15115,     0.15215,     0.15315,     0.15415,     0.15516,     0.15616,     0.15716,     0.15816,     0.15916,     0.16016,     0.16116,     0.16216,     0.16316,     0.16416,     0.16517,     0.16617,     0.16717,
           0.16817,     0.16917,     0.17017,     0.17117,     0.17217,     0.17317,     0.17417,     0.17518,     0.17618,     0.17718,     0.17818,     0.17918,     0.18018,     0.18118,     0.18218,     0.18318,     0.18418,     0.18519,     0.18619,     0.18719,     0.18819,     0.18919,     0.19019,     0.19119,
           0.19219,     0.19319,     0.19419,      0.1952,      0.1962,      0.1972,      0.1982,      0.1992,      0.2002,      0.2012,      0.2022,      0.2032,      0.2042,     0.20521,     0.20621,     0.20721,     0.20821,     0.20921,     0.21021,     0.21121,     0.21221,     0.21321,     0.21421,     0.21522,
           0.21622,     0.21722,     0.21822,     0.21922,     0.22022,     0.22122,     0.22222,     0.22322,     0.22422,     0.22523,     0.22623,     0.22723,     0.22823,     0.22923,     0.23023,     0.23123,     0.23223,     0.23323,     0.23423,     0.23524,     0.23624,     0.23724,     0.23824,     0.23924,
           0.24024,     0.24124,     0.24224,     0.24324,     0.24424,     0.24525,     0.24625,     0.24725,     0.24825,     0.24925,     0.25025,     0.25125,     0.25225,     0.25325,     0.25425,     0.25526,     0.25626,     0.25726,     0.25826,     0.25926,     0.26026,     0.26126,     0.26226,     0.26326,
           0.26426,     0.26527,     0.26627,     0.26727,     0.26827,     0.26927,     0.27027,     0.27127,     0.27227,     0.27327,     0.27427,     0.27528,     0.27628,     0.27728,     0.27828,     0.27928,     0.28028,     0.28128,     0.28228,     0.28328,     0.28428,     0.28529,     0.28629,     0.28729,
           0.28829,     0.28929,     0.29029,     0.29129,     0.29229,     0.29329,     0.29429,      0.2953,      0.2963,      0.2973,      0.2983,      0.2993,      0.3003,      0.3013,      0.3023,      0.3033,      0.3043,     0.30531,     0.30631,     0.30731,     0.30831,     0.30931,     0.31031,     0.31131,
           0.31231,     0.31331,     0.31431,     0.31532,     0.31632,     0.31732,     0.31832,     0.31932,     0.32032,     0.32132,     0.32232,     0.32332,     0.32432,     0.32533,     0.32633,     0.32733,     0.32833,     0.32933,     0.33033,     0.33133,     0.33233,     0.33333,     0.33433,     0.33534,
           0.33634,     0.33734,     0.33834,     0.33934,     0.34034,     0.34134,     0.34234,     0.34334,     0.34434,     0.34535,     0.34635,     0.34735,     0.34835,     0.34935,     0.35035,     0.35135,     0.35235,     0.35335,     0.35435,     0.35536,     0.35636,     0.35736,     0.35836,     0.35936,
           0.36036,     0.36136,     0.36236,     0.36336,     0.36436,     0.36537,     0.36637,     0.36737,     0.36837,     0.36937,     0.37037,     0.37137,     0.37237,     0.37337,     0.37437,     0.37538,     0.37638,     0.37738,     0.37838,     0.37938,     0.38038,     0.38138,     0.38238,     0.38338,
           0.38438,     0.38539,     0.38639,     0.38739,     0.38839,     0.38939,     0.39039,     0.39139,     0.39239,     0.39339,     0.39439,      0.3954,      0.3964,      0.3974,      0.3984,      0.3994,      0.4004,      0.4014,      0.4024,      0.4034,      0.4044,     0.40541,     0.40641,     0.40741,

# Individual Results for an Image

In [2]:
#first go at visualizing results on an image
img_folders = os.listdir("/Users/jonathanzhu/nematostella_videos/imgs/")
img_folders
#results_vis = best_model(["/Users/jonathanzhu/nematostella_videos/imgs/wt_16C_3_dpf_03_27_2026_celldish/"])

['wt_25c_6_dpf_fert_04_10_2026',
 'rpa_bb_16C_9_dpf_celldish_04_02_2026',
 'rpa_bb_16C_3_dpf_movedtodish_03_27_2026',
 'rpa_aa_16C_3_dpf_fert_04_24_2026',
 'wt_25c_7_dpf_fert_04_10_2026',
 'wt_16C_2_dpf_03_26_2026',
 'rpa_bb_25C_8_dpf_celldish_04_01_2026',
 'rpa_aa_25C_3_dpf_03_27_2026_celldish',
 'rpa_bb_16C_3_dpf_fert_04_24_2026',
 'glw_ac_16c_3_dpf_fert_04_24_2026',
 'rpa_bb_16C_6_dpf_celldish_03_30_2026',
 'wt_25c_4_dpf_fert_04_10_2026',
 'wt_25C_6_dpf_celldish_03_30_2026',
 'rpa_aa_16C_3_dpf_movedtodish_03_27_2026',
 'wt_25c_5_dpf_fert_04_10_2026',
 'wt_16C_8_dpf_celldish_04_01_2026',
 'rpa_aa_16C_6_dpf_fert_04_24_2026',
 'wt_16C_3_dpf_03_27_2026_celldish',
 '.DS_Store',
 'rpa_bb_16C_2_dpf_03_26_2026',
 'rpa_aa_25C_8_dpf_celldish_04_01_2026',
 'rpa_aa_16C_7_dpf_fert_04_24_2026',
 'glw_ac_16c_5_dpf_fert_04_24_2026',
 'rpa_bb_25C_3_dpf_03_27_2026_celldish',
 'rpa_bb_16C_5_dpf_fert_04_24_2026',
 'rpa_aa_16C_6_dpf_celldish_03_30_2026',
 'rpa_bb_16C_6_dpf_fert_04_24_2026',
 'glw_ac_16c_6_dpf_fert_04_24_2026',
 'rpa_aa_25C_2_dpf_03_26_2026',
 'rpa_aa_16C_9_dpf_celldish_04_02_2026',
 'glw_ac_25C_2_dpf_03_26_2026',
 'glw_ac_16c_7_dpf_fert_04_24_2026',
 'rpa_aa_16C_5_dpf_fert_04_24_2026',
 'rpa_bb_16C_7_dpf_fert_04_24_2026',
 'rpa_aa_25C_3_dpf_fert_04_24_2026',
 'wt_25C_8_dpf_celldish_04_01_2026',
 'wt_16c_6_dpf_fert_04_10_2026',
 'wt_16C_6_dpf_celldish_03_30_2026',
 'rpa_bb_25C_6_dpf_celldish_03_30_2026',
 'rpa_aa_16C_3_dpf_03_27_2026_celldish',
 'rpa_bb_16C_8_dpf_celldish_04_01_2026',
 'wt_16c_7_dpf_fert_04_10_2026',
 'wt_16c_4_dpf_fert_04_10_2026',
 'wt_16C_9_dpf_celldish_04_02_2026',
 'wt_25C_2_dpf_03_26_2026',
 'glw_ac_25c_3_dpf_fert_04_24_2026',
 'rpa_bb_25C_3_dpf_fert_04_24_2026',
 'wt_16c_5_dpf_fert_04_10_2026',
 'glw_ac_16C_2_dpf_03_26_2026',
 'rpa_aa_25C_4_dpf_fert_04_10_2026_take2',
 'rpa_aa_16C_2_dpf_03_26_2026',
 'rpa_aa_25C_6_dpf_fert_04_24_2026',
 'rpa_bb_25C_5_dpf_fert_04_24_2026',
 'glw_ac_25c_5_dpf_fert_04_24_2026',
 'rpa_aa_25C_7_dpf_fert_04_24_2026',
 'glw_ac_25c_6_dpf_fert_04_24_2026',
 'rpa_aa_25C_6_dpf_celldish_03_30_2026',
 'rpa_bb_25C_6_dpf_fert_04_24_2026',
 'rpa_bb_16C_3_dpf_03_27_2026_celldish',
 'rpa_aa_16C_8_dpf_celldish_04_01_2026',
 'rpa_bb_25C_7_dpf_fert_04_24_2026',
 'rpa_aa_25C_5_dpf_fert_04_24_2026',
 'glw_ac_25c_7_dpf_fert_04_24_2026',
 'rpa_bb_25C_2_dpf_03_26_2026',
 'wt_16C_6_dpf_movedtodish_03_30_2026',
 'wt_16c_5_dpf_fert_04_24_2026',
 'wt_16c_6_dpf_fert_04_24_2026',
 'wt_16c_7_dpf_fert_04_24_2026',
 'glw_ac_25c_6_dpf_fert_04_10_2026',
 'rpa_aa_25C_4_dpf_fert_04_10_2026',
 'rpa_bb_25C_6_dpf_fert_04_10_2026',
 'rpa_bb_25C_7_dpf_fert_04_10_2026',
 'rpa_aa_25C_5_dpf_fert_04_10_2026',
 'glw_ac_25c_7_dpf_fert_04_10_2026',
 'wt_16C_3_dpf_movedtodish_03_27_2026',
 'rpa_aa_25C_6_dpf_fert_04_10_2026',
 'glw_ac_25c_4_dpf_fert_04_10_2026',
 'rpa_bb_25C_4_dpf_fert_04_10_2026',
 'wt_16c_3_dpf_fert_04_24_2026',
 'wt_25C_3_dpf_celldish_03_27_2026',
 'rpa_bb_25C_5_dpf_fert_04_10_2026',
 'glw_ac_25c_5_dpf_fert_04_10_2026',
 'rpa_aa_25C_7_dpf_fert_04_10_2026',
 'glw_ac_16C_3_dpf_movedtodish_03_27_2026',
 'wt_25c_5_dpf_fert_04_24_2026',
 'rpa_bb_16C_6_dpf_movedtodish_03_30_2026',
 'wt_25c_6_dpf_fert_04_24_2026',
 'rpa_aa_16C_6_dpf_movedtodish_03_30_2026',
 'wt_25c_7_dpf_fert_04_24_2026',
 'rpa_bb_16C_6_dpf_fert_04_10_2026',
 'rpa_aa_16C_4_dpf_fert_04_10_2026',
 'glw_ac_16c_6_dpf_fert_04_10_2026',
 'glw_ac_16c_7_dpf_fert_04_10_2026',
 'rpa_aa_16C_5_dpf_fert_04_10_2026',
 'rpa_bb_16C_7_dpf_fert_04_10_2026',
 'wt_25c_3_dpf_fert_04_24_2026',
 'rpa_bb_16C_4_dpf_fert_04_10_2026',
 'glw_ac_16c_4_dpf_fert_04_10_2026',
 'rpa_aa_16C_6_dpf_fert_04_10_2026',
 'rpa_aa_16C_7_dpf_fert_04_10_2026',
 'glw_ac_16c_5_dpf_fert_04_10_2026',
 'rpa_bb_16C_5_dpf_fert_04_10_2026']

In [3]:
images_list = os.listdir("/Users/jonathanzhu/nematostella_videos/imgs/" + img_folders[0])
images_list

['wt_25c_6_dpf_fert_04_10_20260158.png',
 'wt_25c_6_dpf_fert_04_10_20261246.png',
 'wt_25c_6_dpf_fert_04_10_20261520.png',
 'wt_25c_6_dpf_fert_04_10_20261534.png',
 'wt_25c_6_dpf_fert_04_10_20261252.png',
 'wt_25c_6_dpf_fert_04_10_20260164.png',
 'wt_25c_6_dpf_fert_04_10_20260602.png',
 'wt_25c_6_dpf_fert_04_10_20261508.png',
 'wt_25c_6_dpf_fert_04_10_20260616.png',
 'wt_25c_6_dpf_fert_04_10_20260170.png',
 'wt_25c_6_dpf_fert_04_10_20261285.png',
 'wt_25c_6_dpf_fert_04_10_20260825.png',
 'wt_25c_6_dpf_fert_04_10_20260831.png',
 'wt_25c_6_dpf_fert_04_10_20261291.png',
 'wt_25c_6_dpf_fert_04_10_20260819.png',
 'wt_25c_6_dpf_fert_04_10_20261722.png',
 'wt_25c_6_dpf_fert_04_10_20261044.png',
 'wt_25c_6_dpf_fert_04_10_20261050.png',
 'wt_25c_6_dpf_fert_04_10_20260428.png',
 'wt_25c_6_dpf_fert_04_10_20261736.png',
 'wt_25c_6_dpf_fert_04_10_20260400.png',
 'wt_25c_6_dpf_fert_04_10_20261078.png',
 'wt_25c_6_dpf_fert_04_10_20260366.png',
 'wt_25c_6_dpf_fert_04_10_20260372.png',
 'wt_25c_6_dpf_fert_04_10_20260414.png',
 'wt_25c_6_dpf_fert_04_10_20260399.png',
 'wt_25c_6_dpf_fert_04_10_20261087.png',
 'wt_25c_6_dpf_fert_04_10_20261093.png',
 'wt_25c_6_dpf_fert_04_10_20261656.png',
 'wt_25c_6_dpf_fert_04_10_20260548.png',
 'wt_25c_6_dpf_fert_04_10_20261130.png',
 'wt_25c_6_dpf_fert_04_10_20261124.png',
 'wt_25c_6_dpf_fert_04_10_20261642.png',
 'wt_25c_6_dpf_fert_04_10_20260574.png',
 'wt_25c_6_dpf_fert_04_10_20260212.png',
 'wt_25c_6_dpf_fert_04_10_20260206.png',
 'wt_25c_6_dpf_fert_04_10_20261118.png',
 'wt_25c_6_dpf_fert_04_10_20260560.png',
 'wt_25c_6_dpf_fert_04_10_20261695.png',
 'wt_25c_6_dpf_fert_04_10_20261681.png',
 'wt_25c_6_dpf_fert_04_10_20261332.png',
 'wt_25c_6_dpf_fert_04_10_20261454.png',
 'wt_25c_6_dpf_fert_04_10_20260992.png',
 'wt_25c_6_dpf_fert_04_10_20261440.png',
 'wt_25c_6_dpf_fert_04_10_20260986.png',
 'wt_25c_6_dpf_fert_04_10_20261326.png',
 'wt_25c_6_dpf_fert_04_10_20260038.png',
 'wt_25c_6_dpf_fert_04_10_20260010.png',
 'wt_25c_6_dpf_fert_04_10_20260776.png',
 'wt_25c_6_dpf_fert_04_10_20261468.png',
 'wt_25c_6_dpf_fert_04_10_20260762.png',
 'wt_25c_6_dpf_fert_04_10_20260004.png',
 'wt_25c_6_dpf_fert_04_10_20261497.png',
 'wt_25c_6_dpf_fert_04_10_20260951.png',
 'wt_25c_6_dpf_fert_04_10_20260789.png',
 'wt_25c_6_dpf_fert_04_10_20261483.png',
 'wt_25c_6_dpf_fert_04_10_20260945.png',
 'wt_25c_6_dpf_fert_04_10_20260979.png',
 'wt_25c_6_dpf_fert_04_10_20260978.png',
 'wt_25c_6_dpf_fert_04_10_20260944.png',
 'wt_25c_6_dpf_fert_04_10_20261482.png',
 'wt_25c_6_dpf_fert_04_10_20260788.png',
 'wt_25c_6_dpf_fert_04_10_20260950.png',
 'wt_25c_6_dpf_fert_04_10_20261496.png',
 'wt_25c_6_dpf_fert_04_10_20260763.png',
 'wt_25c_6_dpf_fert_04_10_20260005.png',
 'wt_25c_6_dpf_fert_04_10_20260011.png',
 'wt_25c_6_dpf_fert_04_10_20261469.png',
 'wt_25c_6_dpf_fert_04_10_20260777.png',
 'wt_25c_6_dpf_fert_04_10_20260987.png',
 'wt_25c_6_dpf_fert_04_10_20261441.png',
 'wt_25c_6_dpf_fert_04_10_20260039.png',
 'wt_25c_6_dpf_fert_04_10_20261327.png',
 'wt_25c_6_dpf_fert_04_10_20261333.png',
 'wt_25c_6_dpf_fert_04_10_20260993.png',
 'wt_25c_6_dpf_fert_04_10_20261455.png',
 'wt_25c_6_dpf_fert_04_10_20261680.png',
 'wt_25c_6_dpf_fert_04_10_20261694.png',
 'wt_25c_6_dpf_fert_04_10_20261119.png',
 'wt_25c_6_dpf_fert_04_10_20260207.png',
 'wt_25c_6_dpf_fert_04_10_20260561.png',
 'wt_25c_6_dpf_fert_04_10_20260575.png',
 'wt_25c_6_dpf_fert_04_10_20260213.png',
 'wt_25c_6_dpf_fert_04_10_20261125.png',
 'wt_25c_6_dpf_fert_04_10_20261643.png',
 'wt_25c_6_dpf_fert_04_10_20260549.png',
 'wt_25c_6_dpf_fert_04_10_20261657.png',
 'wt_25c_6_dpf_fert_04_10_20261131.png',
 'wt_25c_6_dpf_fert_04_10_20261092.png',
 'wt_25c_6_dpf_fert_04_10_20261086.png',
 'wt_25c_6_dpf_fert_04_10_20260398.png',
 'wt_25c_6_dpf_fert_04_10_20260373.png',
 'wt_25c_6_dpf_fert_04_10_20260415.png',
 'wt_25c_6_dpf_fert_04_10_20260401.png',
 'wt_25c_6_dpf_fert_04_10_20260367.png',
 'wt_25c_6_dpf_fert_04_10_20261079.png',
 'wt_25c_6_dpf_fert_04_10_20261051.png',
 'wt_25c_6_dpf_fert_04_10_20261737.png',
 'wt_25c_6_dpf_fert_04_10_20260429.png',
 'wt_25c_6_dpf_fert_04_10_20261723.png',
 'wt_25c_6_dpf_fert_04_10_20261045.png',
 'wt_25c_6_dpf_fert_04_10_20260818.png',
 'wt_25c_6_dpf_fert_04_10_20260830.png',
 'wt_25c_6_dpf_fert_04_10_20261290.png',
 'wt_25c_6_dpf_fert_04_10_20261284.png',
 'wt_25c_6_dpf_fert_04_10_20260824.png',
 'wt_25c_6_dpf_fert_04_10_20260617.png',
 'wt_25c_6_dpf_fert_04_10_20261509.png',
 'wt_25c_6_dpf_fert_04_10_20260171.png',
 'wt_25c_6_dpf_fert_04_10_20260165.png',
 'wt_25c_6_dpf_fert_04_10_20260603.png',
 'wt_25c_6_dpf_fert_04_10_20261535.png',
 'wt_25c_6_dpf_fert_04_10_20261253.png',
 'wt_25c_6_dpf_fert_04_10_20261247.png',
 'wt_25c_6_dpf_fert_04_10_20260159.png',
 'wt_25c_6_dpf_fert_04_10_20261521.png',
 'wt_25c_6_dpf_fert_04_10_20261251.png',
 'wt_25c_6_dpf_fert_04_10_20261537.png',
 'wt_25c_6_dpf_fert_04_10_20260629.png',
 'wt_25c_6_dpf_fert_04_10_20261523.png',
 'wt_25c_6_dpf_fert_04_10_20261245.png',
 'wt_25c_6_dpf_fert_04_10_20260173.png',
 'wt_25c_6_dpf_fert_04_10_20260615.png',
 'wt_25c_6_dpf_fert_04_10_20260601.png',
 'wt_25c_6_dpf_fert_04_10_20260167.png',
 'wt_25c_6_dpf_fert_04_10_20261279.png',
 'wt_25c_6_dpf_fert_04_10_20261292.png',
 'wt_25c_6_dpf_fert_04_10_20260832.png',
 'wt_25c_6_dpf_fert_04_10_20260826.png',
 'wt_25c_6_dpf_fert_04_10_20261286.png',
 'wt_25c_6_dpf_fert_04_10_20260198.png',
 'wt_25c_6_dpf_fert_04_10_20261735.png',
 'wt_25c_6_dpf_fert_04_10_20261053.png',
 'wt_25c_6_dpf_fert_04_10_20261047.png',
 'wt_25c_6_dpf_fert_04_10_20260359.png',
 'wt_25c_6_dpf_fert_04_10_20261721.png',
 'wt_25c_6_dpf_fert_04_10_20260417.png',
 'wt_25c_6_dpf_fert_04_10_20261709.png',
 'wt_25c_6_dpf_fert_04_10_20260371.png',
 'wt_25c_6_dpf_fert_04_10_20260365.png',
 'wt_25c_6_dpf_fert_04_10_20260403.png',
 'wt_25c_6_dpf_fert_04_10_20261090.png',
 'wt_25c_6_dpf_fert_04_10_20261084.png',
 'wt_25c_6_dpf_fert_04_10_20261641.png',
 'wt_25c_6_dpf_fert_04_10_20260239.png',
 'wt_25c_6_dpf_fert_04_10_20261127.png',
 'wt_25c_6_dpf_fert_04_10_20261133.png',
 'wt_25c_6_dpf_fert_04_10_20261655.png',
 'wt_25c_6_dpf_fert_04_10_20260563.png',
 'wt_25c_6_dpf_fert_04_10_20260205.png',
 'wt_25c_6_dpf_fert_04_10_20260211.png',
 'wt_25c_6_dpf_fert_04_10_20261669.png',
 'wt_25c_6_dpf_fert_04_10_20260577.png',
 'wt_25c_6_dpf_fert_04_10_20261682.png',
 'wt_25c_6_dpf_fert_04_10_20260588.png',
 'wt_25c_6_dpf_fert_04_10_20261696.png',
 'wt_25c_6_dpf_fert_04_10_20261325.png',
 'wt_25c_6_dpf_fert_04_10_20261443.png',
 'wt_25c_6_dpf_fert_04_10_20260985.png',
 'wt_25c_6_dpf_fert_04_10_20260749.png',
 'wt_25c_6_dpf_fert_04_10_20261457.png',
 'wt_25c_6_dpf_fert_04_10_20260991.png',
 'wt_25c_6_dpf_fert_04_10_20261331.png',
 'wt_25c_6_dpf_fert_04_10_20261319.png',
 'wt_25c_6_dpf_fert_04_10_20260007.png',
 'wt_25c_6_dpf_fert_04_10_20260761.png',
 'wt_25c_6_dpf_fert_04_10_20260775.png',
 'wt_25c_6_dpf_fert_04_10_20260013.png',
 'wt_25c_6_dpf_fert_04_10_20261480.png',
 'wt_25c_6_dpf_fert_04_10_20260946.png',
 'wt_25c_6_dpf_fert_04_10_20261494.png',
 'wt_25c_6_dpf_fert_04_10_20260952.png',
 'wt_25c_6_dpf_fert_04_10_20260953.png',
 'wt_25c_6_dpf_fert_04_10_20261495.png',
 'wt_25c_6_dpf_fert_04_10_20260947.png',
 'wt_25c_6_dpf_fert_04_10_20261481.png',
 'wt_25c_6_dpf_fert_04_10_20260774.png',
 'wt_25c_6_dpf_fert_04_10_20260012.png',
 'wt_25c_6_dpf_fert_04_10_20260006.png',
 'wt_25c_6_dpf_fert_04_10_20261318.png',
 'wt_25c_6_dpf_fert_04_10_20260760.png',
 'wt_25c_6_dpf_fert_04_10_20260990.png',
 'wt_25c_6_dpf_fert_04_10_20261456.png',
 'wt_25c_6_dpf_fert_04_10_20260748.png',
 'wt_25c_6_dpf_fert_04_10_20261330.png',
 'wt_25c_6_dpf_fert_04_10_20261324.png',
 'wt_25c_6_dpf_fert_04_10_20260984.png',
 'wt_25c_6_dpf_fert_04_10_20261442.png',
 'wt_25c_6_dpf_fert_04_10_20261697.png',
 'wt_25c_6_dpf_fert_04_10_20260589.png',
 'wt_25c_6_dpf_fert_04_10_20261683.png',
 'wt_25c_6_dpf_fert_04_10_20260210.png',
 'wt_25c_6_dpf_fert_04_10_20260576.png',
 'wt_25c_6_dpf_fert_04_10_20261668.png',
 'wt_25c_6_dpf_fert_04_10_20260562.png',
 'wt_25c_6_dpf_fert_04_10_20260204.png',
 'wt_25c_6_dpf_fert_04_10_20261132.png',
 'wt_25c_6_dpf_fert_04_10_20261654.png',
 'wt_25c_6_dpf_fert_04_10_20261640.png',
 'wt_25c_6_dpf_fert_04_10_20261126.png',
 'wt_25c_6_dpf_fert_04_10_20260238.png',
 'wt_25c_6_dpf_fert_04_10_20261085.png',
 'wt_25c_6_dpf_fert_04_10_20261091.png',
 'wt_25c_6_dpf_fert_04_10_20260364.png',
 'wt_25c_6_dpf_fert_04_10_20260402.png',
 'wt_25c_6_dpf_fert_04_10_20261708.png',
 'wt_25c_6_dpf_fert_04_10_20260416.png',
 'wt_25c_6_dpf_fert_04_10_20260370.png',
 'wt_25c_6_dpf_fert_04_10_20260358.png',
 'wt_25c_6_dpf_fert_04_10_20261046.png',
 'wt_25c_6_dpf_fert_04_10_20261720.png',
 'wt_25c_6_dpf_fert_04_10_20261734.png',
 'wt_25c_6_dpf_fert_04_10_20261052.png',
 'wt_25c_6_dpf_fert_04_10_20260827.png',
 'wt_25c_6_dpf_fert_04_10_20260199.png',
 'wt_25c_6_dpf_fert_04_10_20261287.png',
 'wt_25c_6_dpf_fert_04_10_20261293.png',
 'wt_25c_6_dpf_fert_04_10_20260833.png',
 'wt_25c_6_dpf_fert_04_10_20260600.png',
 'wt_25c_6_dpf_fert_04_10_20261278.png',
 'wt_25c_6_dpf_fert_04_10_20260166.png',
 'wt_25c_6_dpf_fert_04_10_20260172.png',
 'wt_25c_6_dpf_fert_04_10_20260614.png',
 'wt_25c_6_dpf_fert_04_10_20261522.png',
 'wt_25c_6_dpf_fert_04_10_20261244.png',
 'wt_25c_6_dpf_fert_04_10_20261250.png',
 'wt_25c_6_dpf_fert_04_10_20260628.png',
 'wt_25c_6_dpf_fert_04_10_20261536.png',
 'wt_25c_6_dpf_fert_04_10_20260610.png',
 'wt_25c_6_dpf_fert_04_10_20260176.png',
 'wt_25c_6_dpf_fert_04_10_20261268.png',
 'wt_25c_6_dpf_fert_04_10_20260162.png',
 'wt_25c_6_dpf_fert_04_10_20260604.png',
 'wt_25c_6_dpf_fert_04_10_20261532.png',
 'wt_25c_6_dpf_fert_04_10_20261254.png',
 'wt_25c_6_dpf_fert_04_10_20261240.png',
 'wt_25c_6_dpf_fert_04_10_20261526.png',
 'wt_25c_6_dpf_fert_04_10_20260638.png',
 'wt_25c_6_dpf_fert_04_10_20260837.png',
 'wt_25c_6_dpf_fert_04_10_20261297.png',
 'wt_25c_6_dpf_fert_04_10_20260189.png',
 'wt_25c_6_dpf_fert_04_10_20261283.png',
 'wt_25c_6_dpf_fert_04_10_20260823.png',
 'wt_25c_6_dpf_fert_04_10_20260374.png',
 'wt_25c_6_dpf_fert_04_10_20260412.png',
 'wt_25c_6_dpf_fert_04_10_20260406.png',
 'wt_25c_6_dpf_fert_04_10_20261718.png',
 'wt_25c_6_dpf_fert_04_10_20260360.png',
 'wt_25c_6_dpf_fert_04_10_20261056.png',
 'wt_25c_6_dpf_fert_04_10_20260348.png',
 'wt_25c_6_dpf_fert_04_10_20261730.png',
 'wt_25c_6_dpf_fert_04_10_20261724.png',
 'wt_25c_6_dpf_fert_04_10_20261042.png',
 'wt_25c_6_dpf_fert_04_10_20261095.png',
 'wt_25c_6_dpf_fert_04_10_20261081.png',
 'wt_25c_6_dpf_fert_04_10_20260200.png',
 'wt_25c_6_dpf_fert_04_10_20261678.png',
 'wt_25c_6_dpf_fert_04_10_20260566.png',
 'wt_25c_6_dpf_fert_04_10_20260572.png',
 'wt_25c_6_dpf_fert_04_10_20260214.png',
 'wt_25c_6_dpf_fert_04_10_20261122.png',
 'wt_25c_6_dpf_fert_04_10_20261644.png',
 'wt_25c_6_dpf_fert_04_10_20261650.png',
 'wt_25c_6_dpf_fert_04_10_20260228.png',
 'wt_25c_6_dpf_fert_04_10_20261136.png',
 'wt_25c_6_dpf_fert_04_10_20260599.png',
 'wt_25c_6_dpf_fert_04_10_20261687.png',
 'wt_25c_6_dpf_fert_04_10_20261693.png',
 'wt_25c_6_dpf_fert_04_10_20260764.png',
 'wt_25c_6_dpf_fert_04_10_20260002.png',
 'wt_25c_6_dpf_fert_04_10_20261308.png',
 'wt_25c_6_dpf_fert_04_10_20260016.png',
 'wt_25c_6_dpf_fert_04_10_20260770.png',
 'wt_25c_6_dpf_fert_04_10_20260758.png',
 'wt_25c_6_dpf_fert_04_10_20260980.png',
 'wt_25c_6_dpf_fert_04_10_20261446.png',
 'wt_25c_6_dpf_fert_04_10_20261320.png',
 'wt_25c_6_dpf_fert_04_10_20261334.png',
 'wt_25c_6_dpf_fert_04_10_20260994.png',
 'wt_25c_6_dpf_fert_04_10_20261452.png',
 'wt_25c_6_dpf_fert_04_10_20260943.png',
 'wt_25c_6_dpf_fert_04_10_20261485.png',
 'wt_25c_6_dpf_fert_04_10_20260957.png',
 'wt_25c_6_dpf_fert_04_10_20261491.png',
 'wt_25c_6_dpf_fert_04_10_20261490.png',
 'wt_25c_6_dpf_fert_04_10_20260956.png',
 'wt_25c_6_dpf_fert_04_10_20261484.png',
 'wt_25c_6_dpf_fert_04_10_20260942.png',
 'wt_25c_6_dpf_fert_04_10_20261335.png',
 'wt_25c_6_dpf_fert_04_10_20261453.png',
 'wt_25c_6_dpf_fert_04_10_20260995.png',
 'wt_25c_6_dpf_fert_04_10_20261447.png',
 'wt_25c_6_dpf_fert_04_10_20260981.png',
 'wt_25c_6_dpf_fert_04_10_20260759.png',
 'wt_25c_6_dpf_fert_04_10_20261321.png',
 'wt_25c_6_dpf_fert_04_10_20260017.png',
 'wt_25c_6_dpf_fert_04_10_20261309.png',
 'wt_25c_6_dpf_fert_04_10_20260771.png',
 'wt_25c_6_dpf_fert_04_10_20260765.png',
 'wt_25c_6_dpf_fert_04_10_20260003.png',
 'wt_25c_6_dpf_fert_04_10_20261692.png',
 'wt_25c_6_dpf_fert_04_10_20261686.png',
 'wt_25c_6_dpf_fert_04_10_20260598.png',
 'wt_25c_6_dpf_fert_04_10_20261651.png',
 'wt_25c_6_dpf_fert_04_10_20261137.png',
 'wt_25c_6_dpf_fert_04_10_20260229.png',
 'wt_25c_6_dpf_fert_04_10_20261123.png',
 'wt_25c_6_dpf_fert_04_10_20261645.png',
 'wt_25c_6_dpf_fert_04_10_20260573.png',
 'wt_25c_6_dpf_fert_04_10_20260215.png',
 'wt_25c_6_dpf_fert_04_10_20260201.png',
 'wt_25c_6_dpf_fert_04_10_20260567.png',
 'wt_25c_6_dpf_fert_04_10_20261679.png',
 'wt_25c_6_dpf_fert_04_10_20261080.png',
 'wt_25c_6_dpf_fert_04_10_20261094.png',
 'wt_25c_6_dpf_fert_04_10_20261725.png',
 'wt_25c_6_dpf_fert_04_10_20261043.png',
 'wt_25c_6_dpf_fert_04_10_20260349.png',
 'wt_25c_6_dpf_fert_04_10_20261057.png',
 'wt_25c_6_dpf_fert_04_10_20261731.png',
 'wt_25c_6_dpf_fert_04_10_20261719.png',
 'wt_25c_6_dpf_fert_04_10_20260407.png',
 'wt_25c_6_dpf_fert_04_10_20260361.png',
 'wt_25c_6_dpf_fert_04_10_20260375.png',
 'wt_25c_6_dpf_fert_04_10_20260413.png',
 'wt_25c_6_dpf_fert_04_10_20261282.png',
 'wt_25c_6_dpf_fert_04_10_20260822.png',
 'wt_25c_6_dpf_fert_04_10_20260836.png',
 'wt_25c_6_dpf_fert_04_10_20260188.png',
 'wt_25c_6_dpf_fert_04_10_20261296.png',
 'wt_25c_6_dpf_fert_04_10_20261241.png',
 'wt_25c_6_dpf_fert_04_10_20260639.png',
 'wt_25c_6_dpf_fert_04_10_20261527.png',
 'wt_25c_6_dpf_fert_04_10_20261533.png',
 'wt_25c_6_dpf_fert_04_10_20261255.png',
 'wt_25c_6_dpf_fert_04_10_20260163.png',
 'wt_25c_6_dpf_fert_04_10_20260605.png',
 'wt_25c_6_dpf_fert_04_10_20260611.png',
 'wt_25c_6_dpf_fert_04_10_20261269.png',
 'wt_25c_6_dpf_fert_04_10_20260177.png',
 'wt_25c_6_dpf_fert_04_10_20261519.png',
 'wt_25c_6_dpf_fert_04_10_20260607.png',
 'wt_25c_6_dpf_fert_04_10_20260161.png',
 'wt_25c_6_dpf_fert_04_10_20260175.png',
 'wt_25c_6_dpf_fert_04_10_20260613.png',
 'wt_25c_6_dpf_fert_04_10_20261525.png',
 'wt_25c_6_dpf_fert_04_10_20261243.png',
 'wt_25c_6_dpf_fert_04_10_20260149.png',
 'wt_25c_6_dpf_fert_04_10_20261257.png',
 'wt_25c_6_dpf_fert_04_10_20261531.png',
 'wt_25c_6_dpf_fert_04_10_20260808.png',
 'wt_25c_6_dpf_fert_04_10_20260820.png',
 'wt_25c_6_dpf_fert_04_10_20261280.png',
 'wt_25c_6_dpf_fert_04_10_20261294.png',
 'wt_25c_6_dpf_fert_04_10_20260834.png',
 'wt_25c_6_dpf_fert_04_10_20260363.png',
 'wt_25c_6_dpf_fert_04_10_20260405.png',
 'wt_25c_6_dpf_fert_04_10_20260411.png',
 'wt_25c_6_dpf_fert_04_10_20261069.png',
 'wt_25c_6_dpf_fert_04_10_20260377.png',
 'wt_25c_6_dpf_fert_04_10_20261041.png',
 'wt_25c_6_dpf_fert_04_10_20260439.png',
 'wt_25c_6_dpf_fert_04_10_20261727.png',
 'wt_25c_6_dpf_fert_04_10_20261733.png',
 'wt_25c_6_dpf_fert_04_10_20261055.png',
 'wt_25c_6_dpf_fert_04_10_20261082.png',
 'wt_25c_6_dpf_fert_04_10_20260388.png',
 'wt_25c_6_dpf_fert_04_10_20261096.png',
 'wt_25c_6_dpf_fert_04_10_20260217.png',
 'wt_25c_6_dpf_fert_04_10_20261109.png',
 'wt_25c_6_dpf_fert_04_10_20260571.png',
 'wt_25c_6_dpf_fert_04_10_20260565.png',
 'wt_25c_6_dpf_fert_04_10_20260203.png',
 'wt_25c_6_dpf_fert_04_10_20261135.png',
 'wt_25c_6_dpf_fert_04_10_20261653.png',
 'wt_25c_6_dpf_fert_04_10_20261647.png',
 'wt_25c_6_dpf_fert_04_10_20260559.png',
 'wt_25c_6_dpf_fert_04_10_20261121.png',
 'wt_25c_6_dpf_fert_04_10_20261690.png',
 'wt_25c_6_dpf_fert_04_10_20261684.png',
 'wt_25c_6_dpf_fert_04_10_20260773.png',
 'wt_25c_6_dpf_fert_04_10_20260015.png',
 'wt_25c_6_dpf_fert_04_10_20260001.png',
 'wt_25c_6_dpf_fert_04_10_20260767.png',
 'wt_25c_6_dpf_fert_04_10_20261479.png',
 'wt_25c_6_dpf_fert_04_10_20260997.png',
 'wt_25c_6_dpf_fert_04_10_20261451.png',
 'wt_25c_6_dpf_fert_04_10_20261337.png',
 'wt_25c_6_dpf_fert_04_10_20260029.png',
 'wt_25c_6_dpf_fert_04_10_20261323.png',
 'wt_25c_6_dpf_fert_04_10_20260983.png',
 'wt_25c_6_dpf_fert_04_10_20261445.png',
 'wt_25c_6_dpf_fert_04_10_20260968.png',
 'wt_25c_6_dpf_fert_04_10_20260954.png',
 'wt_25c_6_dpf_fert_04_10_20261492.png',
 'wt_25c_6_dpf_fert_04_10_20260940.png',
 'wt_25c_6_dpf_fert_04_10_20261486.png',
 'wt_25c_6_dpf_fert_04_10_20260798.png',
 'wt_25c_6_dpf_fert_04_10_20260799.png',
 'wt_25c_6_dpf_fert_04_10_20261487.png',
 'wt_25c_6_dpf_fert_04_10_20260941.png',
 'wt_25c_6_dpf_fert_04_10_20261493.png',
 'wt_25c_6_dpf_fert_04_10_20260955.png',
 'wt_25c_6_dpf_fert_04_10_20260969.png',
 'wt_25c_6_dpf_fert_04_10_20261322.png',
 'wt_25c_6_dpf_fert_04_10_20261444.png',
 'wt_25c_6_dpf_fert_04_10_20260982.png',
 'wt_25c_6_dpf_fert_04_10_20261450.png',
 'wt_25c_6_dpf_fert_04_10_20260996.png',
 'wt_25c_6_dpf_fert_04_10_20260028.png',
 'wt_25c_6_dpf_fert_04_10_20261336.png',
 'wt_25c_6_dpf_fert_04_10_20261478.png',
 'wt_25c_6_dpf_fert_04_10_20260766.png',
 'wt_25c_6_dpf_fert_04_10_20260772.png',
 'wt_25c_6_dpf_fert_04_10_20260014.png',
 'wt_25c_6_dpf_fert_04_10_20261685.png',
 'wt_25c_6_dpf_fert_04_10_20261691.png',
 'wt_25c_6_dpf_fert_04_10_20260558.png',
 'wt_25c_6_dpf_fert_04_10_20261646.png',
 'wt_25c_6_dpf_fert_04_10_20261120.png',
 'wt_25c_6_dpf_fert_04_10_20261134.png',
 'wt_25c_6_dpf_fert_04_10_20261652.png',
 'wt_25c_6_dpf_fert_04_10_20260564.png',
 'wt_25c_6_dpf_fert_04_10_20260202.png',
 'wt_25c_6_dpf_fert_04_10_20261108.png',
 'wt_25c_6_dpf_fert_04_10_20260216.png',
 'wt_25c_6_dpf_fert_04_10_20260570.png',
 'wt_25c_6_dpf_fert_04_10_20261097.png',
 'wt_25c_6_dpf_fert_04_10_20260389.png',
 'wt_25c_6_dpf_fert_04_10_20261083.png',
 'wt_25c_6_dpf_fert_04_10_20261732.png',
 'wt_25c_6_dpf_fert_04_10_20261054.png',
 'wt_25c_6_dpf_fert_04_10_20261040.png',
 'wt_25c_6_dpf_fert_04_10_20261726.png',
 'wt_25c_6_dpf_fert_04_10_20260438.png',
 'wt_25c_6_dpf_fert_04_10_20260410.png',
 'wt_25c_6_dpf_fert_04_10_20260376.png',
 'wt_25c_6_dpf_fert_04_10_20261068.png',
 'wt_25c_6_dpf_fert_04_10_20260362.png',
 'wt_25c_6_dpf_fert_04_10_20260404.png',
 'wt_25c_6_dpf_fert_04_10_20261295.png',
 'wt_25c_6_dpf_fert_04_10_20260835.png',
 'wt_25c_6_dpf_fert_04_10_20260821.png',
 'wt_25c_6_dpf_fert_04_10_20261281.png',
 'wt_25c_6_dpf_fert_04_10_20260809.png',
 'wt_25c_6_dpf_fert_04_10_20261256.png',
 'wt_25c_6_dpf_fert_04_10_20260148.png',
 'wt_25c_6_dpf_fert_04_10_20261530.png',
 'wt_25c_6_dpf_fert_04_10_20261524.png',
 'wt_25c_6_dpf_fert_04_10_20261242.png',
 'wt_25c_6_dpf_fert_04_10_20260174.png',
 'wt_25c_6_dpf_fert_04_10_20260612.png',
 'wt_25c_6_dpf_fert_04_10_20260606.png',
 'wt_25c_6_dpf_fert_04_10_20261518.png',
 'wt_25c_6_dpf_fert_04_10_20260160.png',
 'wt_25c_6_dpf_fert_04_10_20260885.png',
 'wt_25c_6_dpf_fert_04_10_20261543.png',
 'wt_25c_6_dpf_fert_04_10_20261225.png',
 'wt_25c_6_dpf_fert_04_10_20261231.png',
 'wt_25c_6_dpf_fert_04_10_20260891.png',
 'wt_25c_6_dpf_fert_04_10_20261557.png',
 'wt_25c_6_dpf_fert_04_10_20260649.png',
 'wt_25c_6_dpf_fert_04_10_20260661.png',
 'wt_25c_6_dpf_fert_04_10_20260107.png',
 'wt_25c_6_dpf_fert_04_10_20261219.png',
 'wt_25c_6_dpf_fert_04_10_20260113.png',
 'wt_25c_6_dpf_fert_04_10_20260675.png',
 'wt_25c_6_dpf_fert_04_10_20260846.png',
 'wt_25c_6_dpf_fert_04_10_20261580.png',
 'wt_25c_6_dpf_fert_04_10_20260852.png',
 'wt_25c_6_dpf_fert_04_10_20261594.png',
 'wt_25c_6_dpf_fert_04_10_20261027.png',
 'wt_25c_6_dpf_fert_04_10_20260339.png',
 'wt_25c_6_dpf_fert_04_10_20261741.png',
 'wt_25c_6_dpf_fert_04_10_20261755.png',
 'wt_25c_6_dpf_fert_04_10_20261033.png',
 'wt_25c_6_dpf_fert_04_10_20260305.png',
 'wt_25c_6_dpf_fert_04_10_20260463.png',
 'wt_25c_6_dpf_fert_04_10_20260477.png',
 'wt_25c_6_dpf_fert_04_10_20261769.png',
 'wt_25c_6_dpf_fert_04_10_20260311.png',
 'wt_25c_6_dpf_fert_04_10_20261782.png',
 'wt_25c_6_dpf_fert_04_10_20261796.png',
 'wt_25c_6_dpf_fert_04_10_20260488.png',
 'wt_25c_6_dpf_fert_04_10_20261153.png',
 'wt_25c_6_dpf_fert_04_10_20261635.png',
 'wt_25c_6_dpf_fert_04_10_20261621.png',

In [4]:
#if running this: restart the kernel and skip all the portions with best_model.val
#you will get the error of RuntimeError: Inference tensors do not track version counter

best_model = YOLO("runs/detect/train-4/weights/best.pt")
results_vis = best_model("/Users/jonathanzhu/nematostella_videos/imgs/" + img_folders[0] + "/" + images_list[0])
for r in results_vis:
    boxes = r.boxes  # Boxes object for bounding box outputs
    masks = r.masks  # Masks object for segmentation masks outputs
    keypoints = r.keypoints  # Keypoints object for pose outputs
    probs = r.probs  # Probs object for classification outputs
    obb = r.obb  # Oriented boxes object for OBB outputs
    r.show()  # display to screen
    r.save(filename="result_test.png")  # save to disk

image 1/1 /Users/jonathanzhu/nematostella_videos/imgs/wt_25c_6_dpf_fert_04_10_2026/wt_25c_6_dpf_fert_04_10_20260158.png: 640x640 14 Planulas, 9 Polyps, 61.7ms
Speed: 2.4ms preprocess, 61.7ms inference, 0.1ms postprocess per image at shape (1, 3, 640, 640)

In [5]:
boxes.data

tensor([[5.5759e+02, 6.6118e+02, 5.8070e+02, 6.7711e+02, 9.4271e-01, 1.0000e+00],
        [8.4869e+02, 7.0201e+02, 8.5754e+02, 7.1272e+02, 9.3240e-01, 0.0000e+00],
        [7.9783e+02, 6.4432e+02, 8.1944e+02, 6.6274e+02, 9.2697e-01, 1.0000e+00],
        [7.4826e+02, 7.0776e+02, 7.5814e+02, 7.1819e+02, 9.2407e-01, 0.0000e+00],
        [5.3611e+02, 3.5992e+02, 5.4676e+02, 3.7011e+02, 9.2207e-01, 0.0000e+00],
        [3.8803e+02, 3.2693e+02, 3.9944e+02, 3.3775e+02, 9.1080e-01, 0.0000e+00],
        [3.2859e+02, 1.6222e+02, 3.4463e+02, 1.7804e+02, 9.0965e-01, 1.0000e+00],
        [6.9980e+02, 1.4522e+02, 7.1358e+02, 1.7446e+02, 9.0280e-01, 1.0000e+00],
        [4.6722e+02, 1.6435e+02, 4.8033e+02, 1.7419e+02, 8.9996e-01, 0.0000e+00],
        [4.2034e+02, 5.1453e+02, 4.3001e+02, 5.2424e+02, 8.9826e-01, 0.0000e+00],
        [4.2429e+02, 5.7293e+02, 4.3173e+02, 5.8088e+02, 8.6077e-01, 0.0000e+00],
        [2.8675e+02, 3.9055e+02, 2.9953e+02, 4.0358e+02, 8.1966e-01, 0.0000e+00],
        [1.4450e+02, 6.8369e+02, 1.5340e+02, 6.9300e+02, 7.9385e-01, 0.0000e+00],
        [4.0536e+02, 3.3171e+02, 4.1889e+02, 3.4216e+02, 7.9070e-01, 0.0000e+00],
        [3.0216e+02, 2.1440e+02, 3.2499e+02, 2.4438e+02, 7.8912e-01, 1.0000e+00],
        [9.4539e+02, 5.4232e+02, 9.5213e+02, 5.4944e+02, 7.2049e-01, 0.0000e+00],
        [4.5783e+02, 7.6251e+02, 4.7081e+02, 7.8187e+02, 7.0413e-01, 1.0000e+00],
        [3.9906e+02, 4.6534e+02, 4.1093e+02, 4.7726e+02, 5.6095e-01, 0.0000e+00],
        [6.2689e+02, 6.0305e+02, 6.5157e+02, 6.3675e+02, 5.0663e-01, 1.0000e+00],
        [3.9894e+02, 4.6541e+02, 4.1096e+02, 4.7715e+02, 3.7983e-01, 0.0000e+00],
        [9.4076e+02, 5.9007e+02, 9.4797e+02, 5.9777e+02, 3.4955e-01, 0.0000e+00],
        [4.4997e+02, 8.9078e+02, 4.6424e+02, 9.0066e+02, 3.2243e-01, 1.0000e+00],
        [4.5683e+02, 7.7178e+02, 4.6858e+02, 7.8287e+02, 2.5467e-01, 1.0000e+00]])

In [7]:
df_res = pd.DataFrame(np.array(boxes.data))
df_res

/var/folders/px/b7vc3nh913zb_m0x36ncftj00000gn/T/ipykernel_12103/1638245846.py:1: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  df_res = pd.DataFrame(np.array(boxes.data))

             0           1           2           3         4    5
0   557.586121  661.183105  580.698059  677.107971  0.942711  1.0
1   848.687317  702.012817  857.541931  712.724487  0.932403  0.0
2   797.833618  644.323486  819.435425  662.739746  0.926968  1.0
3   748.263428  707.756714  758.144043  718.186951  0.924072  0.0
4   536.110962  359.921844  546.759460  370.110138  0.922071  0.0
5   388.031128  326.925964  399.440491  337.754120  0.910799  0.0
6   328.585571  162.219955  344.634308  178.037628  0.909652  1.0
7   699.795959  145.218094  713.582642  174.458450  0.902802  1.0
8   467.221497  164.346786  480.329712  174.194046  0.899955  0.0
9   420.338226  514.527466  430.005035  524.239136  0.898264  0.0
10  424.289001  572.934448  431.729492  580.876526  0.860771  0.0
11  286.753357  390.546234  299.532166  403.584839  0.819663  0.0
12  144.504364  683.687622  153.399460  692.997925  0.793855  0.0
13  405.356995  331.712128  418.890533  342.164185  0.790701  0.0
14  302.162415  214.401627  324.994904  244.383987  0.789119  1.0
15  945.393616  542.316101  952.134644  549.435730  0.720487  0.0
16  457.834625  762.511658  470.812317  781.871704  0.704131  1.0
17  399.057312  465.339813  410.934418  477.261810  0.560949  0.0
18  626.888428  603.047791  651.565918  636.747742  0.506630  1.0
19  398.938782  465.411011  410.961578  477.145233  0.379828  0.0
20  940.759033  590.067993  947.970703  597.769348  0.349554  0.0
21  449.969086  890.783081  464.237396  900.655029  0.322434  1.0
22  456.829346  771.781921  468.579315  782.870239  0.254670  1.0

In [8]:
df_res.columns = ["x1", "y1", "x2", "y2", "conf", "class"]
df_res

            x1          y1          x2          y2      conf  class
0   557.586121  661.183105  580.698059  677.107971  0.942711    1.0
1   848.687317  702.012817  857.541931  712.724487  0.932403    0.0
2   797.833618  644.323486  819.435425  662.739746  0.926968    1.0
3   748.263428  707.756714  758.144043  718.186951  0.924072    0.0
4   536.110962  359.921844  546.759460  370.110138  0.922071    0.0
5   388.031128  326.925964  399.440491  337.754120  0.910799    0.0
6   328.585571  162.219955  344.634308  178.037628  0.909652    1.0
7   699.795959  145.218094  713.582642  174.458450  0.902802    1.0
8   467.221497  164.346786  480.329712  174.194046  0.899955    0.0
9   420.338226  514.527466  430.005035  524.239136  0.898264    0.0
10  424.289001  572.934448  431.729492  580.876526  0.860771    0.0
11  286.753357  390.546234  299.532166  403.584839  0.819663    0.0
12  144.504364  683.687622  153.399460  692.997925  0.793855    0.0
13  405.356995  331.712128  418.890533  342.164185  0.790701    0.0
14  302.162415  214.401627  324.994904  244.383987  0.789119    1.0
15  945.393616  542.316101  952.134644  549.435730  0.720487    0.0
16  457.834625  762.511658  470.812317  781.871704  0.704131    1.0
17  399.057312  465.339813  410.934418  477.261810  0.560949    0.0
18  626.888428  603.047791  651.565918  636.747742  0.506630    1.0
19  398.938782  465.411011  410.961578  477.145233  0.379828    0.0
20  940.759033  590.067993  947.970703  597.769348  0.349554    0.0
21  449.969086  890.783081  464.237396  900.655029  0.322434    1.0
22  456.829346  771.781921  468.579315  782.870239  0.254670    1.0

In [9]:
df_res.insert(0, "image_filename", images_list[0])

In [10]:
df_res

,image_filename,x1,y1,x2,y2,conf,class
0,wt_25c_6_dpf_fert_04_10_20260158.png,557.586121,661.183105,580.698059,677.107971,0.942711,1.0
1,wt_25c_6_dpf_fert_04_10_20260158.png,848.687317,702.012817,857.541931,712.724487,0.932403,0.0
2,wt_25c_6_dpf_fert_04_10_20260158.png,797.833618,644.323486,819.435425,662.739746,0.926968,1.0
3,wt_25c_6_dpf_fert_04_10_20260158.png,748.263428,707.756714,758.144043,718.186951,0.924072,0.0
4,wt_25c_6_dpf_fert_04_10_20260158.png,536.110962,359.921844,546.759460,370.110138,0.922071,0.0
5,wt_25c_6_dpf_fert_04_10_20260158.png,388.031128,326.925964,399.440491,337.754120,0.910799,0.0
6,wt_25c_6_dpf_fert_04_10_20260158.png,328.585571,162.219955,344.634308,178.037628,0.909652,1.0
7,wt_25c_6_dpf_fert_04_10_20260158.png,699.795959,145.218094,713.582642,174.458450,0.902802,1.0
8,wt_25c_6_dpf_fert_04_10_20260158.png,467.221497,164.346786,480.329712,174.194046,0.899955,0.0
9,wt_25c_6_dpf_fert_04_10_20260158.png,420.338226,514.527466,430.005035,524.239136,0.898264,0.0
10,wt_25c_6_dpf_fert_04_10_20260158.png,424.289001,572.934448,431.729492,580.876526,0.860771,0.0
11,wt_25c_6_dpf_fert_04_10_20260158.png,286.753357,390.546234,299.532166,403.584839,0.819663,0.0
12,wt_25c_6_dpf_fert_04_10_20260158.png,144.504364,683.687622,153.399460,692.997925,0.793855,0.0
13,wt_25c_6_dpf_fert_04_10_20260158.png,405.356995,331.712128,418.890533,342.164185,0.790701,0.0
14,wt_25c_6_dpf_fert_04_10_20260158.png,302.162415,214.401627,324.994904,244.383987,0.789119,1.0
15,wt_25c_6_dpf_fert_04_10_20260158.png,945.393616,542.316101,952.134644,549.435730,0.720487,0.0
16,wt_25c_6_dpf_fert_04_10_20260158.png,457.834625,762.511658,470.812317,781.871704,0.704131,1.0
17,wt_25c_6_dpf_fert_04_10_20260158.png,399.057312,465.339813,410.934418,477.261810,0.560949,0.0
18,wt_25c_6_dpf_fert_04_10_20260158.png,626.888428,603.047791,651.565918,636.747742,0.506630,1.0
19,wt_25c_6_dpf_fert_04_10_20260158.png,398.938782,465.411011,410.961578,477.145233,0.379828,0.0
20,wt_25c_6_dpf_fert_04_10_20260158.png,940.759033,590.067993,947.970703,597.769348,0.349554,0.0
21,wt_25c_6_dpf_fert_04_10_20260158.png,449.969086,890.783081,464.237396,900.655029,0.322434,1.0
22,wt_25c_6_dpf_fert_04_10_20260158.png,456.829346,771.781921,468.579315,782.870239,0.254670,1.0

In [11]:
df_res.to_csv("result_test.csv")